version: 2.1

jobs:
  build_webapp:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run:
          name: Web app
          command: |
            cd src/frontend
            npm install
            npm run build
  test_webapp:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run:
          name: Web app
          command: |
            cd src/frontend
            npm install
            npm test
  test_server:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run:
          name: Server
          command: |
            cd src/backend
            npm install
            npm test
workflows:
  version: 2
  build-test:
    jobs:
      - build_webapp
      - test_webapp:
          requires:
            - build_webapp
      - test_server:
          requires:
            - build_webapp
