version: 2.1

jobs:
  build:
    docker: # run the steps with Docker
      - image: circleci/node:lts
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - run:
          name: npm-install
          command: npm install
      - run:
          name: build-scss
          command: npm run build-scss
      - run:
          name: npm-test
          command: npm test
